---
management:
    hostname: SROS01
    location: "Site A" 
    systemIP: 10.1.1.1

mda:
    - id: 1
      mda_type: a8-1gb-v3-sfp
      ethernet: true
    - id: 3
      mda_type: a6-em
    - id: 6
      mda_type:  a12-sdi

ports:
    - id: 1/1/1
      type: ethernet
      description: "to SROS02"
      mode: network
      encap: "null"
    - id: 1/1/3
      type: ethernet
      description: "to Switch 1"
      mode: access
      encap: dot1q
    - id: 1/6/1
      type: rs232
      description: "to Cpipe"

router_interface:
    - id: "to-SROS02-01"
      address: 10.0.0.0/31
      port: 1/1/1

      
ospf:
    - id: 0.0.0.1
      interfaces:
        - id: "system"
        - id: "to-SROS02-01"
          type: "point-to-point"

services:
    - id: 11001
      description: "Data and Voice VPRN"
      type: vprn
      customer: 200
      interfaces:
        - id: "21001"
          description: "Management VPLS"
          address: 10.2.5.1/24
          vpls: "M1"
          saps:
            - id: 1/1/3:1
        - id: "21002"
          description: "Data VPLS"
          address: 10.2.6.1/24
          vpls: "D2"
          saps:
            - id: 1/1/3:2
          dhcp: true
    - id: 21000
      type: m-vpls
      customer: 200
      saps:
        - id: 1/1/3:0

timing:
    - id: 1
      port: 1/1/1
